### ISSUE TITLE
Item Height

### ISSUE THREAD

**Issue by AndreBastos23** [Aidurber/react-picky#28]
## Here's what went wrong:
Is it possible to set the item height as auto? I have diferent values coming from the DB and right now they are overlapping each other, since there is strings that contain only a few characters, and some that are more long.
Very good library btw :)

**Comment by Aidurber** [comment]
Hi Andre,
Not currently, this is due to react-tiny-virtual-list. Item heights are required to correctly calculate when an item should render.

There is a discussion in #26 about swapping out react-tiny-virtual-list for react-virtualized. It's offers a wide range of different options such as an autosizer and a cellsizer. I'm going to take a look either tonight or tomorrow night at swapping it out to provide a more dynamic virtual list.

Failing finding a nice solution with a nice API, for our needs. Is to remove the internal usage of virtualised lists and leave that up to the developer with a render prop.
Thanks for the issue and the kind words :smiley:

**Comment by Aidurber** [comment]
After swapping out react-tiny-virtual-list for react-virtualized using the CellMeasurer and AutoSizer components. Dynamic heights with the render prop are possible. 
I'll be fixing #26 too before it goes out though. 

Here is an example (no more cutting off!): 
![variable height](https://user-images.githubusercontent.com/5732291/34498106-0538bcb6-eff8-11e7-88dd-a233a50e748b.JPG)

**Comment by AndreBastos23** [comment]
That's awesome, that's really what i need.
I Was going to fork this because i need some more customization, but maybe you have interest in doing this.
Right now, you set the string "x selected" statically. I think you should let people decide what to concat when X elements are selected. For example, right now there is no way to change the string values to my native language. I think a simple prop would resolve this, and this would be more customizable for everyone. Just food for thought :p. 

Maybe even pass a object with all the strings you can change, with your values as defaults.

**Comment by Aidurber** [comment]
Yeah I can make a prop for that, no problem.

**Comment by Aidurber** [comment]
I think there are only 2 hard coded strings: 
- placeholder - which has a prop. 
- x selected - which will have a prop. 

Do you think the prop would suffice? @AndreBastos23
