### ISSUE TITLE
MultiSelect max limit for options

### ISSUE THREAD

**Issue by karankumar89** [Aidurber/react-picky#60]
I was trying to figure out how to limit the number of selections in the multiselect option. For example: if my total number of options are 6, but the user should not select more than 3.

**Comment by Aidurber** [comment]
Hi @karankumar89 
You can prevent the selection of additional items in the onChange callback. Just don't update your state if the length is greater than a certain amount: 

```javascript
  selectMultipleOption(value) {
    console.log("Val", value);
    if (value.length <= 3) {
      this.setState({ arrayValue: value });
    }
  }
```

https://codesandbox.io/s/5wmqw8m24n
There is a little weirdness, if you look at the above link the value that is console logged doesn't reflect the number of items selected. This is because the component maintains its own internal state. However, you should still be able to do this, just use your own state as your single source of truth.
