### ISSUE TITLE
Picky Dropdown retains the filtered list when re-opened.

### ISSUE THREAD

**Issue by karankumar89** [Aidurber/react-picky#73]
## Version
2.0.5

## Here's what went wrong:
When you select the dropdown, type a search string on the filter and close the dropdown and open it again - the dropdown shows the filtered list with the filter input empty. The only way to get back to the original state (options) is to type in something and then manually delete it.

You can test it out in the sandbox: https://codesandbox.io/s/qq1689zk3q

Is there a way to access the this.state,filtered flag and set it to false on close of the dropdown list?

**Comment by Aidurber** [comment]
@karankumar89 A new release is building now. 
You should be safe to upgrade to v3.0.1, it shouldn't have been a major bump.

**Comment by karankumar89** [comment]
@Aidurber Thats a quick response. Thanks for fixing it. I'll take the new version. Yea it would be nice to get the additional prop.

**Comment by karankumar89** [comment]
@Aidurber Hey i updated to the v3.0.1 but looks like the issue is still there, is it supposed to fixed from the library or should i do something from my end by using the onFilterChange prop?

**Comment by karankumar89** [comment]
![image](https://user-images.githubusercontent.com/10858252/46980055-4665b380-d088-11e8-9a84-6ec242473263.png)

![image](https://user-images.githubusercontent.com/10858252/46980099-68f7cc80-d088-11e8-965e-a19ea61a5af2.png)

**Comment by Aidurber** [comment]
Hmm I wonder if I messed up the build. I'll investigate later.

**Comment by karankumar89** [comment]
Sounds Good! I'll wait for the change :sunglasses:

**Comment by Aidurber** [comment]
Thanks @karankumar89 
There's plenty to be improved, for large lists I'd recommend using: 
https://github.com/clauderic/react-tiny-virtual-list
or the larger but with more flexibility: 
https://github.com/bvaughn/react-virtualized

With > 500 items you will notice a lag, less so in a production build of React. 

Regardless, I appreciate your kind words! :)

You were right, by the way, the issue wasn't resolved (this is why I should have written a test initially 😄). I had to do some moving around of the Filter. It was getting unmounted when the dropdown closed so my fix to make the Filter a controlled component internally was fruitless. 

I tried to move the filterChange to the Picky component but the performance hit was huge on fairly large lists since the whole tree got re-rendered. 

What I've done is a hack but it works.

**Comment by Riteshgiri** [comment]
This does not work for me.
Is there something I need to change to clear filter field when re-opened?

**Comment by Riteshgiri** [comment]
<img width="626" alt="Screen Shot 2019-09-23 at 5 48 43 PM" src="https://user-images.githubusercontent.com/10654768/65465546-94ec0800-de2a-11e9-905d-30fb45d73005.png">

The content in filter is retained when I click outside and then return back to the filter
